name: Terraform Apply

on:
  push:
    branches: [test]
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload output.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-output
          path: output.txt
