name: Terraform Pipeline

on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to run'
        required: true
        default: 'plan'
        type: choice
        options:
          - init-fmt
          - validate-plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Format
        if: github.event_name == 'push' || github.event.inputs.action == 'init-fmt'
        run: |
          terraform init
          terraform fmt -check

      - name: Terraform Validate & Plan
        if: github.event_name == 'push' || github.event.inputs.action == 'validate-plan'
        run: |
          terraform validate
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

      - name: Upload output.txt
        if: github.event.inputs.action != 'destroy'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-output
          path: output.txt
