name: Terraform Destroy 

on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform destroy'
        required: true
        default: 'destroy'
        type: choice
        options:
          - destroy
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
